// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/webhook": {
            "post": {
                "description": "To receive incoming message from Telegram",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot"
                ],
                "summary": "Webhook",
                "parameters": [
                    {
                        "description": "Telegram incoming chat",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teo_internal_services_bot_model.TelegramIncommingChat"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "teo_internal_common.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "teo_internal_services_bot_model.Chat": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "teo_internal_services_bot_model.From": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_bot": {
                    "type": "boolean"
                },
                "language_code": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "teo_internal_services_bot_model.TelegramIncommingChat": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/teo_internal_services_bot_model.UserMessage"
                },
                "update_id": {
                    "type": "integer"
                }
            }
        },
        "teo_internal_services_bot_model.UserMessage": {
            "type": "object",
            "properties": {
                "chat": {
                    "$ref": "#/definitions/teo_internal_services_bot_model.Chat"
                },
                "date": {
                    "type": "integer"
                },
                "from": {
                    "$ref": "#/definitions/teo_internal_services_bot_model.From"
                },
                "message_id": {
                    "type": "integer"
                },
                "text": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TEO API",
	Description:      "TEO - Telegram Ollama Integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
