// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/webhook/bot": {
            "post": {
                "description": "To receive incoming message from RabbitMQ consumer",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot"
                ],
                "summary": "Bot",
                "parameters": [
                    {
                        "description": "Telegram incoming chat",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teo_internal_pkg.TelegramIncommingChat"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_pkg.TelegramSendMessageStatus"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/webhook/telegram": {
            "post": {
                "description": "To receive incoming message from Telegram and push to Queue",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Bot"
                ],
                "summary": "Queue",
                "parameters": [
                    {
                        "description": "Telegram incoming chat",
                        "name": "book",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/teo_internal_pkg.TelegramIncommingChat"
                        }
                    }
                ],
                "responses": {
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/teo_internal_common.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "teo_internal_common.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "error message"
                }
            }
        },
        "teo_internal_pkg.Chat": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "type": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "teo_internal_pkg.Document": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_name": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_unique_id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                },
                "thumb": {
                    "$ref": "#/definitions/teo_internal_pkg.Thumbnail"
                },
                "thumbnail": {
                    "$ref": "#/definitions/teo_internal_pkg.Thumbnail"
                }
            }
        },
        "teo_internal_pkg.From": {
            "type": "object",
            "properties": {
                "first_name": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "is_bot": {
                    "type": "boolean"
                },
                "language_code": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "teo_internal_pkg.Photo": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_unique_id": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "teo_internal_pkg.TelegramIncommingChat": {
            "type": "object",
            "properties": {
                "message": {
                    "$ref": "#/definitions/teo_internal_pkg.UserMessage"
                },
                "update_id": {
                    "type": "integer"
                }
            }
        },
        "teo_internal_pkg.TelegramSendMessageStatus": {
            "type": "object",
            "properties": {
                "description": {
                    "type": "string"
                },
                "error_code": {
                    "type": "integer"
                },
                "ok": {
                    "type": "boolean"
                },
                "result": {
                    "$ref": "#/definitions/teo_internal_pkg.UserMessage"
                }
            }
        },
        "teo_internal_pkg.Thumbnail": {
            "type": "object",
            "properties": {
                "file_id": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_unique_id": {
                    "type": "string"
                },
                "height": {
                    "type": "integer"
                },
                "width": {
                    "type": "integer"
                }
            }
        },
        "teo_internal_pkg.UserMessage": {
            "type": "object",
            "properties": {
                "caption": {
                    "type": "string"
                },
                "chat": {
                    "$ref": "#/definitions/teo_internal_pkg.Chat"
                },
                "date": {
                    "type": "integer"
                },
                "document": {
                    "$ref": "#/definitions/teo_internal_pkg.Document"
                },
                "from": {
                    "$ref": "#/definitions/teo_internal_pkg.From"
                },
                "message_id": {
                    "type": "integer"
                },
                "photo": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/teo_internal_pkg.Photo"
                    }
                },
                "text": {
                    "type": "string"
                },
                "voice": {
                    "$ref": "#/definitions/teo_internal_pkg.Voice"
                }
            }
        },
        "teo_internal_pkg.Voice": {
            "type": "object",
            "properties": {
                "duration": {
                    "type": "integer"
                },
                "file_id": {
                    "type": "string"
                },
                "file_size": {
                    "type": "integer"
                },
                "file_unique_id": {
                    "type": "string"
                },
                "mime_type": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "TEO API",
	Description:      "TEO - Telegram Ollama Integration",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
