services:
  backend:
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      DB_NAME: teo
      MONGODB_URI: mongodb://mongodb:27017
      REDIS_URL: redis://redis:6379
      OLLAMA_BASE_URL: host.docker.internal:11434
    depends_on:
      - mongodb
      - redis

  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

volumes:
  mongodb_data: